import json

# Load the sentiment_dict from the provided JSON
with open('JSON/new_sentiment_dict1.json', 'r') as f:
    sentiment_dict = json.load(f)

# Load the JSON file generated by your previous script
with open('output_article_20231127160445.json', 'r') as f:
    data = json.load(f)

# Check if 'topics' key is present
if 'topics' in data:
    topics = data['topics']

    # Print the available keys in 'topics'
    print(f"Available keys in 'topics': {list(topics.keys())}")

    # Create a list to store results
    results = []

    # Iterate through each topic in 'topics'
    for topic, details in topics.items():
        # Check if 'paragraphs' key is present in topic details
        if 'paragraphs' in details:
            # Extract sentiments for each topic
            for paragraph in details['paragraphs']:
                sentiment = paragraph['sentiment']

                # Check if topic is present in sentiment_dict
                if topic in sentiment_dict:
                    typology_sentiments = sentiment_dict[topic]
                    # Check if sentiment is present in typology_sentiments
                    if sentiment in typology_sentiments:
                        typology_sentiment = typology_sentiments[sentiment]
                        # Store the result in the list
                        results.append({
                            'topic': topic,
                            'sentiment': sentiment,
                            'typology_sentiment': typology_sentiment,
                            'paragraph': paragraph['content']

                        })
                    else:
                        print(f"Warning: Sentiment '{sentiment}' not found for topic '{topic}' in sentiment_dict.")
                else:
                    print(f"Warning: Topic '{topic}' not found in sentiment_dict.")
        else:
            print(f"Warning: 'paragraphs' key not found for topic '{topic}' in 'topics'.")

    # Print or process the results as needed
    for result in results:
        print(f"Topic: {result['topic']}, Sentiment: {result['sentiment']}, Typology Sentiment: {result['typology_sentiment']}, Paragraph: {result['paragraph']}")

    # Save results to a JSON file
    with open('output/results1.json', 'w') as f:
        json.dump(results, f, indent=2)
        print("Results saved to 'results.json'")
else:
    print("Warning: 'topics' key not found in the data.")
